package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItgActivitiesAll generated by hbm2java
 */
public class ItgActivitiesAll  implements java.io.Serializable {


     private Integer activityId;
     private ItgPersonalInfoAll itgPersonalInfoAll;
     private ItgProjectsAll itgProjectsAll;
     private ItgUsersAll itgUsersAll;
     private Long startDay;
     private Long endDay;
     private String month;
     private Long year;
     private String elaboratedBy;
     private String authorizedBy;
     private String attribute1;
     private String attribute2;
     private String attribute3;
     private String attribute4;
     private String numberWeek;
     private Date creationDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;
     private Date weekstartDate;
     private Date weekEndDate;
     private Date recordDate;
     private Date submittedDate;
     private Date approvalDate;
     private String totalHours;
     private String statusTimecard;
     private String comments;
     private String approvalFullName;
     private Set itgActivitiesDetails = new HashSet(0);
     private Set itgInvoiceAlls = new HashSet(0);

    public ItgActivitiesAll() {
       itgPersonalInfoAll = new ItgPersonalInfoAll();
       itgProjectsAll = new ItgProjectsAll();
    }
	
    public ItgActivitiesAll(ItgPersonalInfoAll itgPersonalInfoAll, ItgProjectsAll itgProjectsAll) {
        this.itgPersonalInfoAll = itgPersonalInfoAll;
        this.itgProjectsAll = itgProjectsAll;
    }
    public ItgActivitiesAll(ItgPersonalInfoAll itgPersonalInfoAll, ItgProjectsAll itgProjectsAll, ItgUsersAll itgUsersAll, Long startDay, Long endDay, String month, Long year, String elaboratedBy, String authorizedBy, String attribute1, String attribute2, String attribute3, String attribute4, String numberWeek, Date creationDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy, Date weekstartDate, Date weekEndDate, Date recordDate, Date submittedDate, Date approvalDate, String totalHours, String statusTimecard, String comments, String approvalFullName, Set itgActivitiesDetails, Set itgInvoiceAlls) {
       this.itgPersonalInfoAll = itgPersonalInfoAll;
       this.itgProjectsAll = itgProjectsAll;
       this.itgUsersAll = itgUsersAll;
       this.startDay = startDay;
       this.endDay = endDay;
       this.month = month;
       this.year = year;
       this.elaboratedBy = elaboratedBy;
       this.authorizedBy = authorizedBy;
       this.attribute1 = attribute1;
       this.attribute2 = attribute2;
       this.attribute3 = attribute3;
       this.attribute4 = attribute4;
       this.numberWeek = numberWeek;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.weekstartDate = weekstartDate;
       this.weekEndDate = weekEndDate;
       this.recordDate = recordDate;
       this.submittedDate = submittedDate;
       this.approvalDate = approvalDate;
       this.totalHours = totalHours;
       this.statusTimecard = statusTimecard;
       this.comments = comments;
       this.approvalFullName = approvalFullName;
       this.itgActivitiesDetails = itgActivitiesDetails;
       this.itgInvoiceAlls = itgInvoiceAlls;
    }
   
    public Integer getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
    public ItgPersonalInfoAll getItgPersonalInfoAll() {
        return this.itgPersonalInfoAll;
    }
    
    public void setItgPersonalInfoAll(ItgPersonalInfoAll itgPersonalInfoAll) {
        this.itgPersonalInfoAll = itgPersonalInfoAll;
    }
    public ItgProjectsAll getItgProjectsAll() {
        return this.itgProjectsAll;
    }
    
    public void setItgProjectsAll(ItgProjectsAll itgProjectsAll) {
        this.itgProjectsAll = itgProjectsAll;
    }
    
    public ItgUsersAll getItgUsersAll() {
        return this.itgUsersAll;
    }
    
    public void setItgUsersAll(ItgUsersAll itgUsersAll) {
        this.itgUsersAll = itgUsersAll;
    }
    public Long getStartDay() {
        return this.startDay;
    }
    
    public void setStartDay(Long startDay) {
        this.startDay = startDay;
    }
    public Long getEndDay() {
        return this.endDay;
    }
    
    public void setEndDay(Long endDay) {
        this.endDay = endDay;
    }
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }
    public Long getYear() {
        return this.year;
    }
    
    public void setYear(Long year) {
        this.year = year;
    }
    public String getElaboratedBy() {
        return this.elaboratedBy;
    }
    
    public void setElaboratedBy(String elaboratedBy) {
        this.elaboratedBy = elaboratedBy;
    }
    public String getAuthorizedBy() {
        return this.authorizedBy;
    }
    
    public void setAuthorizedBy(String authorizedBy) {
        this.authorizedBy = authorizedBy;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    public String getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }
    public String getAttribute3() {
        return this.attribute3;
    }
    
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }
    public String getAttribute4() {
        return this.attribute4;
    }
    
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }
    public String getNumberWeek() {
        return this.numberWeek;
    }
    
    public void setNumberWeek(String numberWeek) {
        this.numberWeek = numberWeek;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    
    public Date getWeekstartDate() {
        return this.weekstartDate;
    }
    
    public void setWeekstartDate(Date weekstartDate) {
        this.weekstartDate = weekstartDate;
    }
    public Date getWeekEndDate() {
        return this.weekEndDate;
    }
    
    public void setWeekEndDate(Date weekEndDate) {
        this.weekEndDate = weekEndDate;
    }
    public Date getRecordDate() {
        return this.recordDate;
    }
    
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }
    public Date getSubmittedDate() {
        return this.submittedDate;
    }
    
    public void setSubmittedDate(Date submittedDate) {
        this.submittedDate = submittedDate;
    }
    public Date getApprovalDate() {
        return this.approvalDate;
    }
    
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }
    public String getTotalHours() {
        return this.totalHours;
    }
    
    public void setTotalHours(String totalHours) {
        this.totalHours = totalHours;
    }
    public String getStatusTimecard() {
        return this.statusTimecard;
    }
    
    public void setStatusTimecard(String statusTimecard) {
        this.statusTimecard = statusTimecard;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getApprovalFullName() {
        return this.approvalFullName;
    }
    
    public void setApprovalFullName(String approvalFullName) {
        this.approvalFullName = approvalFullName;
    }
    public Set getItgActivitiesDetails() {
        return this.itgActivitiesDetails;
    }
    
    public void setItgActivitiesDetails(Set itgActivitiesDetails) {
        this.itgActivitiesDetails = itgActivitiesDetails;
    }
    public Set getItgInvoiceAlls() {
        return this.itgInvoiceAlls;
    }
    
    public void setItgInvoiceAlls(Set itgInvoiceAlls) {
        this.itgInvoiceAlls = itgInvoiceAlls;
    }




}


