package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ItgActivitiesDetail generated by hbm2java
 */
public class ItgActivitiesDetail  implements java.io.Serializable {


     private Integer activityReportId;
     private ItgActivitiesAll itgActivitiesAll;
     private String module;
     private String phase;
     private String activity;
     private double mondayHours = 0;
     private double tuesdayHours = 0;
     private double wednesdayHours = 0;
     private double thursdayHours = 0;
     private double fridayHours = 0;
     private double saturdayHours = 0;
     private double sundayHours = 0;
     private Long totalBillableHours;
     private Long totalNonBillableHours;
     private double totalHours = 0;
     private String attribute1;
     private String attribute2;
     private String attribute3;
     private String attribute4;
     private String attribute5;
     private Date creationDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;

    public ItgActivitiesDetail() {
        itgActivitiesAll = new ItgActivitiesAll();
    }

	
    public ItgActivitiesDetail(ItgActivitiesAll itgActivitiesAll) {
        this.itgActivitiesAll = itgActivitiesAll;
    }
    public ItgActivitiesDetail(ItgActivitiesAll itgActivitiesAll, String module, String phase, String activity, Double mondayHours, Double tuesdayHours, Double wednesdayHours, Double thursdayHours, Double fridayHours, Double saturdayHours, Double sundayHours, Long totalBillableHours, Long totalNonBillableHours, Double totalHours, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, Date creationDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy) {
       this.itgActivitiesAll = itgActivitiesAll;
       this.module = module;
       this.phase = phase;
       this.activity = activity;
       this.mondayHours = mondayHours;
       this.tuesdayHours = tuesdayHours;
       this.wednesdayHours = wednesdayHours;
       this.thursdayHours = thursdayHours;
       this.fridayHours = fridayHours;
       this.saturdayHours = saturdayHours;
       this.sundayHours = sundayHours;
       this.totalBillableHours = totalBillableHours;
       this.totalNonBillableHours = totalNonBillableHours;
       this.totalHours = totalHours;
       this.attribute1 = attribute1;
       this.attribute2 = attribute2;
       this.attribute3 = attribute3;
       this.attribute4 = attribute4;
       this.attribute5 = attribute5;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
    }
   
    public Integer getActivityReportId() {
        return this.activityReportId;
    }
    
    public void setActivityReportId(Integer activityReportId) {
        this.activityReportId = activityReportId;
    }
    public ItgActivitiesAll getItgActivitiesAll() {
        return this.itgActivitiesAll;
    }
    
    public void setItgActivitiesAll(ItgActivitiesAll itgActivitiesAll) {
        this.itgActivitiesAll = itgActivitiesAll;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    public String getPhase() {
        return this.phase;
    }
    
    public void setPhase(String phase) {
        this.phase = phase;
    }
    public String getActivity() {
        return this.activity;
    }
    
    public void setActivity(String activity) {
        this.activity = activity;
    }
    public double getMondayHours() {
        return this.mondayHours;
    }
    
    public void setMondayHours(double mondayHours) {
        this.mondayHours = mondayHours;
    }
    public double getTuesdayHours() {
        return this.tuesdayHours;
    }
    
    public void setTuesdayHours(double tuesdayHours) {
        this.tuesdayHours = tuesdayHours;
    }
    public double getWednesdayHours() {
        return this.wednesdayHours;
    }
    
    public void setWednesdayHours(double wednesdayHours) {
        this.wednesdayHours = wednesdayHours;
    }
    public double getThursdayHours() {
        return this.thursdayHours;
    }
    
    public void setThursdayHours(double thursdayHours) {
        this.thursdayHours = thursdayHours;
    }
    public double getFridayHours() {
        return this.fridayHours;
    }
    
    public void setFridayHours(double fridayHours) {
        this.fridayHours = fridayHours;
    }
    public double getSaturdayHours() {
        return this.saturdayHours;
    }
    
    public void setSaturdayHours(double saturdayHours) {
        this.saturdayHours = saturdayHours;
    }
    public double getSundayHours() {
        return this.sundayHours;
    }
    
    public void setSundayHours(double sundayHours) {
        this.sundayHours = sundayHours;
    }
    public Long getTotalBillableHours() {
        return this.totalBillableHours;
    }
    
    public void setTotalBillableHours(Long totalBillableHours) {
        this.totalBillableHours = totalBillableHours;
    }
    public Long getTotalNonBillableHours() {
        return this.totalNonBillableHours;
    }
    
    public void setTotalNonBillableHours(Long totalNonBillableHours) {
        this.totalNonBillableHours = totalNonBillableHours;
    }
    public double getTotalHours() {
        return this.totalHours;
    }
    
    public void setTotalHours(double totalHours) {
        this.totalHours = totalHours;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    public String getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }
    public String getAttribute3() {
        return this.attribute3;
    }
    
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }
    public String getAttribute4() {
        return this.attribute4;
    }
    
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }
    public String getAttribute5() {
        return this.attribute5;
    }
    
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }




}


