package Model;
// Generated 26 nov 2021 18:05:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ItgCompany generated by hbm2java
 */
public class ItgCompany  implements java.io.Serializable {


     private Integer organizacionId;
     private String orgName;
     private String orgType;
     private String pathImg;
     private String pathFacebook;
     private String pathWeb;
     private String pathYoutube;
     private String pathTwitter;
     private String pathLinkedin;
     private String contactName;
     private String contactMail;
     private String contactNumberPhone;
     private String companyAddress;
     private String contactCopyright;
     private String pathReport;
     private String pathFooter;
     private String pathLogo;
     private String reportAddress;
     private Set itgUsersAlls = new HashSet(0);

    public ItgCompany() {
    }

    public ItgCompany(String orgName, String orgType, String pathImg, String pathFacebook, String pathWeb, String pathYoutube, String pathTwitter, String pathLinkedin, String contactName, String contactMail, String contactNumberPhone, String companyAddress, String contactCopyright, String pathReport, String pathFooter, String pathLogo, String reportAddress, Set itgUsersAlls) {
       this.orgName = orgName;
       this.orgType = orgType;
       this.pathImg = pathImg;
       this.pathFacebook = pathFacebook;
       this.pathWeb = pathWeb;
       this.pathYoutube = pathYoutube;
       this.pathTwitter = pathTwitter;
       this.pathLinkedin = pathLinkedin;
       this.contactName = contactName;
       this.contactMail = contactMail;
       this.contactNumberPhone = contactNumberPhone;
       this.companyAddress = companyAddress;
       this.contactCopyright = contactCopyright;
       this.pathReport = pathReport;
       this.pathFooter = pathFooter;
       this.pathLogo = pathLogo;
       this.reportAddress = reportAddress;
       this.itgUsersAlls = itgUsersAlls;
    }
   
    public Integer getOrganizacionId() {
        return this.organizacionId;
    }
    
    public void setOrganizacionId(Integer organizacionId) {
        this.organizacionId = organizacionId;
    }
    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }
    public String getOrgType() {
        return this.orgType;
    }
    
    public void setOrgType(String orgType) {
        this.orgType = orgType;
    }
    public String getPathImg() {
        return this.pathImg;
    }
    
    public void setPathImg(String pathImg) {
        this.pathImg = pathImg;
    }
    public String getPathFacebook() {
        return this.pathFacebook;
    }
    
    public void setPathFacebook(String pathFacebook) {
        this.pathFacebook = pathFacebook;
    }
    public String getPathWeb() {
        return this.pathWeb;
    }
    
    public void setPathWeb(String pathWeb) {
        this.pathWeb = pathWeb;
    }
    public String getPathYoutube() {
        return this.pathYoutube;
    }
    
    public void setPathYoutube(String pathYoutube) {
        this.pathYoutube = pathYoutube;
    }
    public String getPathTwitter() {
        return this.pathTwitter;
    }
    
    public void setPathTwitter(String pathTwitter) {
        this.pathTwitter = pathTwitter;
    }
    public String getPathLinkedin() {
        return this.pathLinkedin;
    }
    
    public void setPathLinkedin(String pathLinkedin) {
        this.pathLinkedin = pathLinkedin;
    }
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    public String getContactMail() {
        return this.contactMail;
    }
    
    public void setContactMail(String contactMail) {
        this.contactMail = contactMail;
    }
    public String getContactNumberPhone() {
        return this.contactNumberPhone;
    }
    
    public void setContactNumberPhone(String contactNumberPhone) {
        this.contactNumberPhone = contactNumberPhone;
    }
    public String getCompanyAddress() {
        return this.companyAddress;
    }
    
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }
    public String getContactCopyright() {
        return this.contactCopyright;
    }
    
    public void setContactCopyright(String contactCopyright) {
        this.contactCopyright = contactCopyright;
    }
    public String getPathReport() {
        return this.pathReport;
    }
    
    public void setPathReport(String pathReport) {
        this.pathReport = pathReport;
    }
    public String getPathFooter() {
        return this.pathFooter;
    }
    
    public void setPathFooter(String pathFooter) {
        this.pathFooter = pathFooter;
    }
    public String getPathLogo() {
        return this.pathLogo;
    }
    
    public void setPathLogo(String pathLogo) {
        this.pathLogo = pathLogo;
    }
    public String getReportAddress() {
        return this.reportAddress;
    }
    
    public void setReportAddress(String reportAddress) {
        this.reportAddress = reportAddress;
    }
    public Set getItgUsersAlls() {
        return this.itgUsersAlls;
    }
    
    public void setItgUsersAlls(Set itgUsersAlls) {
        this.itgUsersAlls = itgUsersAlls;
    }




}


