package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ItgExpenseReportsDetail generated by hbm2java
 */
public class ItgExpenseReportsDetail  implements java.io.Serializable {


     private Integer expenseId;
     private ItgExpenseReportsAll itgExpenseReportsAll;
     private ItgExpenseTypes itgExpenseTypes;
     private Date expenseDate;
     private String specify;
     private String description;
     private Long totalExpense;
     private String attribute1;
     private String attribute2;
     private Long attribute3;
     private Date creationDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;

    public ItgExpenseReportsDetail() {
        itgExpenseReportsAll = new ItgExpenseReportsAll();
        itgExpenseTypes = new ItgExpenseTypes();
        
    }
    
    public ItgExpenseReportsDetail(ItgExpenseReportsAll itgExpenseReportsAll, ItgExpenseTypes itgExpenseTypes) {
        this.itgExpenseReportsAll = itgExpenseReportsAll;
        this.itgExpenseTypes = itgExpenseTypes;
    }

    public ItgExpenseReportsDetail(ItgExpenseReportsAll itgExpenseReportsAll, ItgExpenseTypes itgExpenseTypes, Date expenseDate, String specify, String description, Long totalExpense, String attribute1, String attribute2, Long attribute3, Date creationDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy) {
       this.itgExpenseReportsAll = itgExpenseReportsAll;
       this.itgExpenseTypes = itgExpenseTypes;
       this.expenseDate = expenseDate;
       this.specify = specify;
       this.description = description;
       this.totalExpense = totalExpense;
       this.attribute1 = attribute1;
       this.attribute2 = attribute2;
       this.attribute3 = attribute3;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
    }
   
    public Integer getExpenseId() {
        return this.expenseId;
    }
    
    public void setExpenseId(Integer expenseId) {
        this.expenseId = expenseId;
    }
    public ItgExpenseReportsAll getItgExpenseReportsAll() {
        return this.itgExpenseReportsAll;
    }
    
    public void setItgExpenseReportsAll(ItgExpenseReportsAll itgExpenseReportsAll) {
        this.itgExpenseReportsAll = itgExpenseReportsAll;
    }
    public ItgExpenseTypes getItgExpenseTypes() {
        return this.itgExpenseTypes;
    }
    
    public void setItgExpenseTypes(ItgExpenseTypes itgExpenseTypes) {
        this.itgExpenseTypes = itgExpenseTypes;
    }
    public Date getExpenseDate() {
        return this.expenseDate;
    }
    
    public void setExpenseDate(Date expenseDate) {
        this.expenseDate = expenseDate;
    }
    public String getSpecify() {
        return this.specify;
    }
    
    public void setSpecify(String specify) {
        this.specify = specify;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Long getTotalExpense() {
        return this.totalExpense;
    }
    
    public void setTotalExpense(Long totalExpense) {
        this.totalExpense = totalExpense;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    public String getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }
    public Long getAttribute3() {
        return this.attribute3;
    }
    
    public void setAttribute3(Long attribute3) {
        this.attribute3 = attribute3;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }




}


