package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItgExpenseTypes generated by hbm2java
 */
public class ItgExpenseTypes  implements java.io.Serializable {


     private Integer spendId;
     private ItgProjectsAll itgProjectsAll;
     private String spendName;
     private String description;
     private String attribute1;
     private Long totalMaximo;
     private String attribute2;
     private String attribute3;
     private Date creationDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;
     private Set itgExpenseReportsDetails = new HashSet(0);

    public ItgExpenseTypes() {
    }

    public ItgExpenseTypes(ItgProjectsAll itgProjectsAll, String spendName, String description, String attribute1, Long totalMaximo, String attribute2, String attribute3, Date creationDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy, Set itgExpenseReportsDetails) {
       this.itgProjectsAll = itgProjectsAll;
       this.spendName = spendName;
       this.description = description;
       this.attribute1 = attribute1;
       //this.totalMaximo = totalMaximo;
       this.attribute2 = attribute2;
       this.attribute3 = attribute3;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.itgExpenseReportsDetails = itgExpenseReportsDetails;
    }
   
    public Integer getSpendId() {
        return this.spendId;
    }
    
    public void setSpendId(Integer spendId) {
        this.spendId = spendId;
    }
    public ItgProjectsAll getItgProjectsAll() {
        return this.itgProjectsAll;
    }
    
    public void setItgProjectsAll(ItgProjectsAll itgProjectsAll) {
        this.itgProjectsAll = itgProjectsAll;
    }
    public String getSpendName() {
        return this.spendName;
    }
    
    public void setSpendName(String spendName) {
        this.spendName = spendName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    public Long getTotalMaximo() {
        return this.totalMaximo;
    }
    
    public void setTotalMaximo(Long totalMaximo) {
        this.totalMaximo = totalMaximo;
    }
    public String getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }
    public String getAttribute3() {
        return this.attribute3;
    }
    
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public Set getItgExpenseReportsDetails() {
        return this.itgExpenseReportsDetails;
    }
    
    public void setItgExpenseReportsDetails(Set itgExpenseReportsDetails) {
        this.itgExpenseReportsDetails = itgExpenseReportsDetails;
    }




}


