package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItgExpenseReportsAll generated by hbm2java
 */
public class ItgExpenseReportsAll  implements java.io.Serializable {


     private Integer reportId;
     private ItgPersonalInfoAll itgPersonalApprover;
     private ItgPersonalInfoAll itgPersonalInfoAll;
     private ItgProjectsAll itgProjectsAll;
     private ItgReportStatus itgReportStatus;
     private ItgVouchersStatus itgVouchersStatus;
     private Boolean nameReport;
     private String reasonExpense;
     private Date reportDate;
     private String paymentMethod;
     private byte[] anexos;
     private byte[] pdf;
     private Long totalExpenseReport;
     private String attribute1;
     private byte[] attribute2;
     private Long attribute3;
     private Boolean attribute4;
     private Boolean attribute5;
     private String attribute6;
     private String attribute7;
     private String attribute8;
     private Date creationDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;
     private Set itgExpenseReportsDetails = new HashSet(0);

    public ItgExpenseReportsAll() {
    }

    public ItgExpenseReportsAll(ItgPersonalInfoAll itgPersonalApprover, ItgPersonalInfoAll itgPersonalInfoAll, ItgProjectsAll itgProjectsAll, ItgReportStatus itgReportStatus, ItgVouchersStatus itgVouchersStatus, Boolean nameReport, String reasonExpense, Date reportDate, String paymentMethod, byte[] anexos, byte[] pdf, Long totalExpenseReport, String attribute1, byte[] attribute2, Long attribute3, Boolean attribute4, Boolean attribute5, String attribute6, String attribute7, String attribute8, Date creationDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy, Set itgExpenseReportsDetails) {
       this.itgPersonalApprover = itgPersonalApprover;
       this.itgPersonalInfoAll = itgPersonalInfoAll;
       this.itgProjectsAll = itgProjectsAll;
       this.itgReportStatus = itgReportStatus;
       this.itgVouchersStatus = itgVouchersStatus;
       this.nameReport = nameReport;
       this.reasonExpense = reasonExpense;
       this.reportDate = reportDate;
       this.paymentMethod = paymentMethod;
       this.anexos = anexos;
       this.pdf = pdf;
       this.totalExpenseReport = totalExpenseReport;
       this.attribute1 = attribute1;
       this.attribute2 = attribute2;
       this.attribute3 = attribute3;
       this.attribute4 = attribute4;
       this.attribute5 = attribute5;
       this.attribute6 = attribute6;
       this.attribute7 = attribute7;
       this.attribute8 = attribute8;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.itgExpenseReportsDetails = itgExpenseReportsDetails;
    }
   
    public Integer getReportId() {
        return this.reportId;
    }
    
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }
    public ItgPersonalInfoAll getItgPersonalApprover() {
        return this.itgPersonalApprover;
    }
    
    public void setItgPersonalApprover(ItgPersonalInfoAll itgPersonalApprover) {
        this.itgPersonalApprover= itgPersonalApprover;
    }
    public ItgPersonalInfoAll getItgPersonalInfoAll() {
        return this.itgPersonalInfoAll;
    }
    
    public void setItgPersonalInfoAll(ItgPersonalInfoAll itgPersonalInfoAll) {
        this.itgPersonalInfoAll = itgPersonalInfoAll;
    }
    public ItgProjectsAll getItgProjectsAll() {
        return this.itgProjectsAll;
    }
    
    public void setItgProjectsAll(ItgProjectsAll itgProjectsAll) {
        this.itgProjectsAll = itgProjectsAll;
    }
    public ItgReportStatus getItgReportStatus() {
        return this.itgReportStatus;
    }
    
    public void setItgReportStatus(ItgReportStatus itgReportStatus) {
        this.itgReportStatus = itgReportStatus;
    }
    public ItgVouchersStatus getItgVouchersStatus() {
        return this.itgVouchersStatus;
    }
    
    public void setItgVouchersStatus(ItgVouchersStatus itgVouchersStatus) {
        this.itgVouchersStatus = itgVouchersStatus;
    }
    public Boolean getNameReport() {
        return this.nameReport;
    }
    
    public void setNameReport(Boolean nameReport) {
        this.nameReport = nameReport;
    }
    public String getReasonExpense() {
        return this.reasonExpense;
    }
    
    public void setReasonExpense(String reasonExpense) {
        this.reasonExpense = reasonExpense;
    }
    public Date getReportDate() {
        return this.reportDate;
    }
    
    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public byte[] getAnexos() {
        return this.anexos;
    }
    
    public void setAnexos(byte[] anexos) {
        this.anexos = anexos;
    }
    public byte[] getPdf() {
        return this.pdf;
    }
    
    public void setPdf(byte[] pdf) {
        this.pdf = pdf;
    }
    public Long getTotalExpenseReport() {
        return this.totalExpenseReport;
    }
    
    public void setTotalExpenseReport(Long totalExpenseReport) {
        this.totalExpenseReport = totalExpenseReport;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    public byte[] getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(byte[] attribute2) {
        this.attribute2 = attribute2;
    }
    public Long getAttribute3() {
        return this.attribute3;
    }
    
    public void setAttribute3(Long attribute3) {
        this.attribute3 = attribute3;
    }
    public Boolean getAttribute4() {
        return this.attribute4;
    }
    
    public void setAttribute4(Boolean attribute4) {
        this.attribute4 = attribute4;
    }
    public Boolean getAttribute5() {
        return this.attribute5;
    }
    
    public void setAttribute5(Boolean attribute5) {
        this.attribute5 = attribute5;
    }
    public String getAttribute6() {
        return this.attribute6;
    }
    
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }
    public String getAttribute7() {
        return this.attribute7;
    }
    
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }
    public String getAttribute8() {
        return this.attribute8;
    }
    
    public void setAttribute8(String attribute8) {
        this.attribute8 = attribute8;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public Set getItgExpenseReportsDetails() {
        return this.itgExpenseReportsDetails;
    }
    
    public void setItgExpenseReportsDetails(Set itgExpenseReportsDetails) {
        this.itgExpenseReportsDetails = itgExpenseReportsDetails;
    }




}


