package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ItgListValuesDet generated by hbm2java
 */
public class ItgListValuesDet  implements java.io.Serializable {


     private Integer valueListDetailId;
     private ItgListValues itgListValues;
     private String valueListDetailCode;
     private String valueListDetailValue;
     private String valueListDetailStatus;
     private String attribute1;
     private String attribute2;
     private String attribute3;
     private String attribute4;
     private String attribute5;
     private Date creationDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;

    public ItgListValuesDet() {
        itgListValues = new ItgListValues();
    }

	
    public ItgListValuesDet(ItgListValues itgListValues) {
        this.itgListValues = itgListValues;
    }
    public ItgListValuesDet(ItgListValues itgListValues, String valueListDetailCode, String valueListDetailValue, String valueListDetailStatus, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, Date creationDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy) {
       this.itgListValues = itgListValues;
       this.valueListDetailCode = valueListDetailCode;
       this.valueListDetailValue = valueListDetailValue;
       this.valueListDetailStatus = valueListDetailStatus;
       this.attribute1 = attribute1;
       this.attribute2 = attribute2;
       this.attribute3 = attribute3;
       this.attribute4 = attribute4;
       this.attribute5 = attribute5;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
    }
   
    public Integer getValueListDetailId() {
        return this.valueListDetailId;
    }
    
    public void setValueListDetailId(Integer valueListDetailId) {
        this.valueListDetailId = valueListDetailId;
    }
    public ItgListValues getItgListValues() {
        return this.itgListValues;
    }
    
    public void setItgListValues(ItgListValues itgListValues) {
        this.itgListValues = itgListValues;
    }
    public String getValueListDetailCode() {
        return this.valueListDetailCode;
    }
    
    public void setValueListDetailCode(String valueListDetailCode) {
        this.valueListDetailCode = valueListDetailCode;
    }
    public String getValueListDetailValue() {
        return this.valueListDetailValue;
    }
    
    public void setValueListDetailValue(String valueListDetailValue) {
        this.valueListDetailValue = valueListDetailValue;
    }
    public String getValueListDetailStatus() {
        return this.valueListDetailStatus;
    }
    
    public void setValueListDetailStatus(String valueListDetailStatus) {
        this.valueListDetailStatus = valueListDetailStatus;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    public String getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }
    public String getAttribute3() {
        return this.attribute3;
    }
    
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }
    public String getAttribute4() {
        return this.attribute4;
    }
    
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }
    public String getAttribute5() {
        return this.attribute5;
    }
    
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }




}


