package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1



/**
 * ItgPrueba generated by hbm2java
 */
public class ItgPrueba  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private String attribute1;

    public ItgPrueba() {
    }

    public ItgPrueba(String name, String description, String attribute1) {
       this.name = name;
       this.description = description;
       this.attribute1 = attribute1;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }




}


