package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItgPersonalInfoAll generated by hbm2java
 */
public class ItgPersonalInfoAll  implements java.io.Serializable {


     private Integer personalDataId;
     private ItgCitiesAll itgCitiesAll;
     private ItgCountriesAll itgCountriesAll;
     private ItgEmployeesTypesAll itgEmployeesTypesAll;
     private ItgStatesAll itgStatesAll;
     private String name;
     private String alias;
     private String paternSurname;
     private String maternSurname;
     private Date dischargeDate;
     private String nationality;
     private BigDecimal phoneNumber1;
     private BigDecimal phoneNumber2;
     private BigDecimal phoneNumber3;
     private String curp;
     private String rfc;
     private String mail1;
     private String mail2;
     private String mail3;
     private BigDecimal customerNumber;
     private String delegation;
     private String streetNumber;
     private String colony;
     private String postalCode;
     private String civilStatus;
     private String nss;
     private Date birthdate;
     private Date admissionDate;
     private String job;
     private String superior;
     private Integer employeeNumber;
     private String attribute1;
     private String attribute2;
     private String attribute3;
     private String attribute4;
     private Integer status;
     private Date createDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;
     private Set itgExpenseReportsAlls = new HashSet(0);
     //private Set itgProjectsAlls = new HashSet(0);
     private Set itgActivitiesAlls = new HashSet(0);
     private Set itgUsersAlls = new HashSet(0);
     //private Set itgExpenseReportsAllsForItgPersonalInfoAllPersonalDataId = new HashSet(0);
     //private Set itgProjectsAllsForItgPersonalInfoAllApproverId = new HashSet(0);
    

    public ItgPersonalInfoAll() {
        itgCitiesAll = new ItgCitiesAll();
        itgCountriesAll = new ItgCountriesAll();
        itgEmployeesTypesAll = new ItgEmployeesTypesAll();
        itgStatesAll = new ItgStatesAll();
             
    }

	
    public ItgPersonalInfoAll(ItgCitiesAll itgCitiesAll, ItgCountriesAll itgCountriesAll, ItgEmployeesTypesAll itgEmployeesTypesAll, ItgStatesAll itgStatesAll) {
        this.itgCitiesAll = itgCitiesAll;
        this.itgCountriesAll = itgCountriesAll;
        this.itgEmployeesTypesAll = itgEmployeesTypesAll;
        this.itgStatesAll = itgStatesAll;
    }
    public ItgPersonalInfoAll(ItgCitiesAll itgCitiesAll, ItgCountriesAll itgCountriesAll, ItgEmployeesTypesAll itgEmployeesTypesAll, ItgStatesAll itgStatesAll, String name, String alias, String paternSurname, String maternSurname, Date dischargeDate, String nationality, BigDecimal phoneNumber1, BigDecimal phoneNumber2, BigDecimal phoneNumber3, String curp, String rfc, String mail1, String mail2, String mail3, BigDecimal customerNumber, String delegation, String streetNumber, String colony, String postalCode, String civilStatus, String nss, Date birthdate, Date admissionDate, String job, String superior, Integer employeeNumber, String attribute1, String attribute2, String attribute3, String attribute4, Integer status, Date createDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy, Set itgExpenseReportsAlls, Set itgProjectsAlls, Set itgActivitiesAlls, Set itgUsersAlls) {
       this.itgCitiesAll = itgCitiesAll;
       this.itgCountriesAll = itgCountriesAll;
       this.itgEmployeesTypesAll = itgEmployeesTypesAll;
       this.itgStatesAll = itgStatesAll;
       this.name = name;
       this.alias = alias;
       this.paternSurname = paternSurname;
       this.maternSurname = maternSurname;
       this.dischargeDate = dischargeDate;
       this.nationality = nationality;
       this.phoneNumber1 = phoneNumber1;
       this.phoneNumber2 = phoneNumber2;
       this.phoneNumber3 = phoneNumber3;
       this.curp = curp;
       this.rfc = rfc;
       this.mail1 = mail1;
       this.mail2 = mail2;
       this.mail3 = mail3;
       this.customerNumber = customerNumber;
       this.delegation = delegation;
       this.streetNumber = streetNumber;
       this.colony = colony;
       this.postalCode = postalCode;
       this.civilStatus = civilStatus;
       this.nss = nss;
       this.birthdate = birthdate;
       this.admissionDate = admissionDate;
       this.job = job;
       this.superior = superior;
       this.employeeNumber = employeeNumber;
       this.attribute1 = attribute1;
       this.attribute2 = attribute2;
       this.attribute3 = attribute3;
       this.attribute4 = attribute4;
       this.status = status;
       this.createDate = createDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.itgExpenseReportsAlls = itgExpenseReportsAlls;
       //this.itgProjectsAlls = itgProjectsAlls;
       this.itgActivitiesAlls = itgActivitiesAlls;
       this.itgUsersAlls = itgUsersAlls;
       //this.itgExpenseReportsAllsForItgPersonalInfoAllPersonalDataId = itgExpenseReportsAllsForItgPersonalInfoAllPersonalDataId;
       //this.itgProjectsAllsForItgPersonalInfoAllApproverId = itgProjectsAllsForItgPersonalInfoAllApproverId;
      
    }
   
    public Integer getPersonalDataId() {
        return this.personalDataId;
    }
    
    public void setPersonalDataId(Integer personalDataId) {
        this.personalDataId = personalDataId;
    }
    public ItgCitiesAll getItgCitiesAll() {
        return this.itgCitiesAll;
    }
    
    public void setItgCitiesAll(ItgCitiesAll itgCitiesAll) {
        this.itgCitiesAll = itgCitiesAll;
    }
    public ItgCountriesAll getItgCountriesAll() {
        return this.itgCountriesAll;
    }
    
    public void setItgCountriesAll(ItgCountriesAll itgCountriesAll) {
        this.itgCountriesAll = itgCountriesAll;
    }
    public ItgEmployeesTypesAll getItgEmployeesTypesAll() {
        return this.itgEmployeesTypesAll;
    }
    
    public void setItgEmployeesTypesAll(ItgEmployeesTypesAll itgEmployeesTypesAll) {
        this.itgEmployeesTypesAll = itgEmployeesTypesAll;
    }
    public ItgStatesAll getItgStatesAll() {
        return this.itgStatesAll;
    }
    
    public void setItgStatesAll(ItgStatesAll itgStatesAll) {
        this.itgStatesAll = itgStatesAll;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAlias() {
        if(alias == null){
            return "";
        }else{
        return this.alias;
    }
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getPaternSurname() {
        if(paternSurname == null){
            return "";
        }else{
        return this.paternSurname;
    }
    }
    
    public void setPaternSurname(String paternSurname) {
        this.paternSurname = paternSurname;
    }
    public String getMaternSurname() {
        if(maternSurname == null){
            return "";
        }else{
        return this.maternSurname;
    }
    }
    public void setMaternSurname(String maternSurname) {
        this.maternSurname = maternSurname;
    }
    public Date getDischargeDate() {
        return this.dischargeDate;
    }
    
    public void setDischargeDate(Date dischargeDate) {
        this.dischargeDate = dischargeDate;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public BigDecimal getPhoneNumber1() {
        return this.phoneNumber1;
    }
    
    public void setPhoneNumber1(BigDecimal phoneNumber1) {
        this.phoneNumber1 = phoneNumber1;
    }
    public BigDecimal getPhoneNumber2() {
        return this.phoneNumber2;
    }
    
    public void setPhoneNumber2(BigDecimal phoneNumber2) {
        this.phoneNumber2 = phoneNumber2;
    }
    public BigDecimal getPhoneNumber3() {
        return this.phoneNumber3;
    }
    
    public void setPhoneNumber3(BigDecimal phoneNumber3) {
        this.phoneNumber3 = phoneNumber3;
    }
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getMail1() {
        return this.mail1;
    }
    
    public void setMail1(String mail1) {
        this.mail1 = mail1;
    }
    public String getMail2() {
        return this.mail2;
    }
    
    public void setMail2(String mail2) {
        this.mail2 = mail2;
    }
    public String getMail3() {
        return this.mail3;
    }
    
    public void setMail3(String mail3) {
        this.mail3 = mail3;
    }
    public BigDecimal getCustomerNumber() {
        return this.customerNumber;
    }
    
    public void setCustomerNumber(BigDecimal customerNumber) {
        this.customerNumber = customerNumber;
    }
    public String getDelegation() {
        return this.delegation;
    }
    
    public void setDelegation(String delegation) {
        this.delegation = delegation;
    }
    public String getStreetNumber() {
        return this.streetNumber;
    }
    
    public void setStreetNumber(String streetNumber) {
        this.streetNumber = streetNumber;
    }
    public String getColony() {
        return this.colony;
    }
    
    public void setColony(String colony) {
        this.colony = colony;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getCivilStatus() {
        return this.civilStatus;
    }
    
    public void setCivilStatus(String civilStatus) {
        this.civilStatus = civilStatus;
    }
    public String getNss() {
        return this.nss;
    }
    
    public void setNss(String nss) {
        this.nss = nss;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public Date getAdmissionDate() {
        return this.admissionDate;
    }
    
    public void setAdmissionDate(Date admissionDate) {
        this.admissionDate = admissionDate;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public String getSuperior() {
        return this.superior;
    }
    
    public void setSuperior(String superior) {
        this.superior = superior;
    }
    public Integer getEmployeeNumber() {
        return this.employeeNumber;
    }
    
    public void setEmployeeNumber(Integer employeeNumber) {
        this.employeeNumber = employeeNumber;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    public String getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }
    public String getAttribute3() {
        return this.attribute3;
    }
    
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }
    public String getAttribute4() {
        return this.attribute4;
    }
    
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public Set getItgExpenseReportsAlls() {
        return this.itgExpenseReportsAlls;
    }
    
    public void setItgExpenseReportsAlls(Set itgExpenseReportsAlls) {
        this.itgExpenseReportsAlls = itgExpenseReportsAlls;
    }
   /* public Set getItgProjectsAlls() {
        return this.itgProjectsAlls;
    }
    
    public void setItgProjectsAlls(Set itgProjectsAlls) {
        this.itgProjectsAlls = itgProjectsAlls;
    }*/
    
     public Set getItgActivitiesAlls() {
        return this.itgActivitiesAlls;
    }
    
    public void setItgActivitiesAlls(Set itgActivitiesAlls) {
        this.itgActivitiesAlls = itgActivitiesAlls;
    }
    
       public Set getItgUsersAlls() {
        return this.itgUsersAlls;
    }
    
    public void setItgUsersAlls(Set itgUsersAlls) {
        this.itgUsersAlls = itgUsersAlls;
    }
    
    /*public Set getItgExpenseReportsAllsForItgPersonalInfoAllPersonalDataId() {
        return this.itgExpenseReportsAllsForItgPersonalInfoAllPersonalDataId;
    }
    
    public void setItgExpenseReportsAllsForItgPersonalInfoAllPersonalDataId(Set itgExpenseReportsAllsForItgPersonalInfoAllPersonalDataId) {
        this.itgExpenseReportsAllsForItgPersonalInfoAllPersonalDataId = itgExpenseReportsAllsForItgPersonalInfoAllPersonalDataId;
    }*/
    
   
    /*public Set getItgProjectsAllsForItgPersonalInfoAllApproverId() {
        return this.itgProjectsAllsForItgPersonalInfoAllApproverId;
    }
    
    public void setItgProjectsAllsForItgPersonalInfoAllApproverId(Set itgProjectsAllsForItgPersonalInfoAllApproverId) {
        this.itgProjectsAllsForItgPersonalInfoAllApproverId = itgProjectsAllsForItgPersonalInfoAllApproverId;
    }*/
 




}


