package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItgProjectsAll generated by hbm2java
 */
public class ItgProjectsAll  implements java.io.Serializable {


     private Integer projectId;
     private ItgParties itgParties;
     //private ItgPersonalInfoAll itgPersonalInfoAll;
     private ItgPersonalInfoAll itgPersonalApprover;
     private ItgUserRolesAll itgUserRolesAll;
     private ItgWorkArea itgWorkArea;
     private String projectName;
     private Date projectStartDate;
     private Date projectEndDate;
     private String description;
     private String contractNumber;
     private String workOrder;
     //private Long totalExpense;
     private String deliverables;
     private String workplan;
     private Long projectNumber;
     private String approver;
     private byte[] attribute1;
     private byte[] attribute2;
     private String attribute3;
     private String attribute4;
     private byte[] attribute5;
     private String attribute6;
     private Date creationDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;
     private Set itgActivitiesAlls = new HashSet(0);
     private Set itgExpenseReportsAlls = new HashSet(0);
     //private Set itgInvoiceAlls = new HashSet(0);
     private Set itgExpenseTypeses = new HashSet(0);

    public ItgProjectsAll() {
        itgParties = new ItgParties();
        //itgPersonalInfoAll = new ItgPersonalInfoAll();
       
        
    }
    
    public ItgProjectsAll(ItgParties itgParties, ItgPersonalInfoAll itgPersonalInfoAll){
        this.itgParties = new ItgParties();
        //this.itgPersonalInfoAll = itgPersonalInfoAll;
       
    }
    public ItgProjectsAll(ItgParties itgParties, ItgPersonalInfoAll itgPersonalInfoAll, ItgPersonalInfoAll itgPersonalApprover, ItgUserRolesAll itgUserRolesAll, ItgWorkArea itgWorkArea, String projectName, Date projectStartDate, Date projectEndDate, String description, String contractNumber, String workOrder, String deliverables, String workplan, Long projectNumber, String approver, byte[] attribute1, byte[] attribute2, String attribute3, String attribute4, byte[] attribute5, String attribute6, Date creationDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy, Set itgActivitiesAlls, Set itgExpenseReportsAlls, Set itgExpenseTypeses) {
       this.itgParties = itgParties;
       //this.itgPersonalInfoAll = itgPersonalInfoAll;
       this.itgPersonalApprover = itgPersonalApprover;
       this.itgUserRolesAll = itgUserRolesAll;
       this.itgWorkArea = itgWorkArea;
       this.projectName = projectName;
       this.projectStartDate = projectStartDate;
       this.projectEndDate = projectEndDate;
       this.description = description;
       this.contractNumber = contractNumber;
       this.workOrder = workOrder;
       //this.totalExpense = totalExpense;
       this.deliverables = deliverables;
       this.workplan = workplan;
       this.projectNumber = projectNumber;
       this.approver = approver;
       this.attribute1 = attribute1;
       this.attribute2 = attribute2;
       this.attribute3 = attribute3;
       this.attribute4 = attribute4;
       this.attribute5 = attribute5;
       this.attribute6 = attribute6;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.itgActivitiesAlls = itgActivitiesAlls;
       this.itgExpenseReportsAlls = itgExpenseReportsAlls;
       //this.itgInvoiceAlls = itgInvoiceAlls;
       this.itgExpenseTypeses = itgExpenseTypeses;
    }
   
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
    
    public ItgParties getItgParties() {
        return this.itgParties;
    }
    
    public void setItgParties(ItgParties itgParties) {
        this.itgParties = itgParties;
    }
   /* public ItgPersonalInfoAll getItgPersonalInfoAll() {
        return this.itgPersonalInfoAll;
    }
    
    public void setItgPersonalInfoAll(ItgPersonalInfoAll itgPersonalInfoAll) {
        this.itgPersonalInfoAll = itgPersonalInfoAll;
    }*/
    public ItgPersonalInfoAll getItgPersonalApprover() {
        return this.itgPersonalApprover;
    }
    
    public void setItgPersonalApprover(ItgPersonalInfoAll itgPersonalApprover) {
        this.itgPersonalApprover = itgPersonalApprover;
    }
    public ItgUserRolesAll getItgUserRolesAll() {
        return this.itgUserRolesAll;
    }
    
    public void setItgUserRolesAll(ItgUserRolesAll itgUserRolesAll) {
        this.itgUserRolesAll = itgUserRolesAll;
    }
    public ItgWorkArea getItgWorkArea() {
        return this.itgWorkArea;
    }
    
    public void setItgWorkArea(ItgWorkArea itgWorkArea) {
        this.itgWorkArea = itgWorkArea;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    public Date getProjectStartDate() {
        return this.projectStartDate;
    }
    
    public void setProjectStartDate(Date projectStartDate) {
        this.projectStartDate = projectStartDate;
    }
    public Date getProjectEndDate() {
        return this.projectEndDate;
    }
    
    public void setProjectEndDate(Date projectEndDate) {
        this.projectEndDate = projectEndDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getContractNumber() {
        return this.contractNumber;
    }
    
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }
    public String getWorkOrder() {
        return this.workOrder;
    }
    
    public void setWorkOrder(String workOrder) {
        this.workOrder = workOrder;
    }
    /*public Long getTotalExpense() {
        return this.totalExpense;
    }
    
    public void setTotalExpense(Long totalExpense) {
        this.totalExpense = totalExpense;
    }*/
    
    public String getDeliverables() {
        return this.deliverables;
    }
    
    public void setDeliverables(String deliverables) {
        this.deliverables = deliverables;
    }
    public String getWorkplan() {
        return this.workplan;
    }
    
    public void setWorkplan(String workplan) {
        this.workplan = workplan;
    }
    public Long getProjectNumber() {
        return this.projectNumber;
    }
    
    public void setProjectNumber(Long projectNumber) {
        this.projectNumber = projectNumber;
    }
    public String getApprover() {
        return this.approver;
    }
    
    public void setApprover(String approver) {
        //System.out.println("---->"+this.approver); 
        this.approver = approver;
    }
    public byte[] getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(byte[] attribute1) {
        this.attribute1 = attribute1;
    }
    public byte[] getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(byte[] attribute2) {
        this.attribute2 = attribute2;
    }
    public String getAttribute3() {
        if(attribute1 == null){
            attribute3 = "Vacio";
            return this.attribute3;
        }else{
            attribute3 = "Archivo adjunto";
              return this.attribute3;
        }
    }
    
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }
    public String getAttribute4() {
        if(attribute2 == null){
            attribute4 = "Vacio";
            return this.attribute4;
        }else{
            attribute4 = "Archivo adjunto";
        return this.attribute4;
    }
    }
    
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }
    public byte[] getAttribute5() {
        return this.attribute5;
    }
    
    public void setAttribute5(byte[] attribute5) {
        this.attribute5 = attribute5;
    }
    public String getAttribute6() {
        if(attribute5 == null)
        {
            attribute6 ="Vacio";
            return attribute6;
        }else{
            attribute6 = "Archivo adjunto";
        return this.attribute6;
    }
    }
    
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public Set getItgActivitiesAlls() {
        return this.itgActivitiesAlls;
    }
    
    public void setItgActivitiesAlls(Set itgActivitiesAlls) {
        this.itgActivitiesAlls = itgActivitiesAlls;
    }
    public Set getItgExpenseReportsAlls() {
        return this.itgExpenseReportsAlls;
    }
    
    public void setItgExpenseReportsAlls(Set itgExpenseReportsAlls) {
        this.itgExpenseReportsAlls = itgExpenseReportsAlls;
    }
    /*public Set getItgInvoiceAlls() {
        return this.itgInvoiceAlls;
    }
    
    public void setItgInvoiceAlls(Set itgInvoiceAlls) {
        this.itgInvoiceAlls = itgInvoiceAlls;
    }*/
    public Set getItgExpenseTypeses() {
        return this.itgExpenseTypeses;
    }
    
    public void setItgExpenseTypeses(Set itgExpenseTypeses) {
        this.itgExpenseTypeses = itgExpenseTypeses;
    }




}


