package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItgReportStatus generated by hbm2java
 */
public class ItgReportStatus  implements java.io.Serializable {


     private Integer statusId;
     private String statusName;
     private String description;
     private String attribute1;
     private String attribute2;
     private String attribute3;
     private Date creationDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;
     private Set itgExpenseReportsAlls = new HashSet(0);

    public ItgReportStatus() {
    }

    public ItgReportStatus(String statusName, String description, String attribute1, String attribute2, String attribute3, Date creationDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy, Set itgExpenseReportsAlls) {
       this.statusName = statusName;
       this.description = description;
       this.attribute1 = attribute1;
       this.attribute2 = attribute2;
       this.attribute3 = attribute3;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.itgExpenseReportsAlls = itgExpenseReportsAlls;
    }
   
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }
    public String getStatusName() {
        return this.statusName;
    }
    
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    public String getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }
    public String getAttribute3() {
        return this.attribute3;
    }
    
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public Set getItgExpenseReportsAlls() {
        return this.itgExpenseReportsAlls;
    }
    
    public void setItgExpenseReportsAlls(Set itgExpenseReportsAlls) {
        this.itgExpenseReportsAlls = itgExpenseReportsAlls;
    }




}


