package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItgStatesAll generated by hbm2java
 */
public class ItgStatesAll  implements java.io.Serializable {


     private Integer stateId;
     private ItgCountriesAll itgCountriesAll;
     private String stateName;
     private String attribute1;
     private String attribute2;
     private String attribute3;
     private String attribute4;
     private String attribute5;
     private Date creationDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;
     private Set itgPersonalInfoAlls = new HashSet(0);
     private Set itgCitiesAlls = new HashSet(0);
     private Set itgPartieses = new HashSet(0);

    public ItgStatesAll() {
        itgCountriesAll = new ItgCountriesAll();
            
    }
    public ItgStatesAll(ItgCountriesAll itgCountriesAll){
        this.itgCountriesAll = itgCountriesAll;
    }

    public ItgStatesAll(ItgCountriesAll itgCountriesAll, String stateName, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, Date creationDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy, Set itgPersonalInfoAlls, Set itgCitiesAlls, Set itgPartieses) {
       this.itgCountriesAll = itgCountriesAll;
       this.stateName = stateName;
       this.attribute1 = attribute1;
       this.attribute2 = attribute2;
       this.attribute3 = attribute3;
       this.attribute4 = attribute4;
       this.attribute5 = attribute5;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.itgPersonalInfoAlls = itgPersonalInfoAlls;
       this.itgCitiesAlls = itgCitiesAlls;
       this.itgPartieses = itgPartieses;
    }
   
    public Integer getStateId() {
        return this.stateId;
    }
    
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }
    public ItgCountriesAll getItgCountriesAll() {
        return this.itgCountriesAll;
    }
    
    public void setItgCountriesAll(ItgCountriesAll itgCountriesAll) {
        this.itgCountriesAll = itgCountriesAll;
    }
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    public String getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }
    public String getAttribute3() {
        return this.attribute3;
    }
    
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }
    public String getAttribute4() {
        return this.attribute4;
    }
    
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }
    public String getAttribute5() {
        return this.attribute5;
    }
    
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public Set getItgPersonalInfoAlls() {
        return this.itgPersonalInfoAlls;
    }
    
    public void setItgPersonalInfoAlls(Set itgPersonalInfoAlls) {
        this.itgPersonalInfoAlls = itgPersonalInfoAlls;
    }
    public Set getItgCitiesAlls() {
        return this.itgCitiesAlls;
    }
    
    public void setItgCitiesAlls(Set itgCitiesAlls) {
        this.itgCitiesAlls = itgCitiesAlls;
    }
    public Set getItgPartieses() {
        return this.itgPartieses;
    }
    
    public void setItgPartieses(Set itgPartieses) {
        this.itgPartieses = itgPartieses;
    }

}


