package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItgUserRolesAll generated by hbm2java
 */
public class ItgUserRolesAll  implements java.io.Serializable {


     private Integer userRoleId;
     private ItgWorkArea itgWorkArea;
     private String userRoleName;
     private String userRoleKey;
     private String userRoleDescription;
     private String attribute1;
     private String attribute2;
     private String attribute3;
     private String attribute4;
     private String attribute5;
     private Date creationDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;
     private Set itgUsersAlls = new HashSet(0);
     //private Set itgProjectsAlls = new HashSet(0);

    public ItgUserRolesAll() {
        itgWorkArea = new ItgWorkArea();
    }
    
    public ItgUserRolesAll(ItgWorkArea itgWorkArea){
        this.itgWorkArea = itgWorkArea;
    }

    public ItgUserRolesAll(ItgWorkArea itgWorkArea, String userRoleName, String userRoleKey, String userRoleDescription, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, Date creationDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy, Set itgUsersAlls) {
       this.itgWorkArea = itgWorkArea;
       this.userRoleName = userRoleName;
       this.userRoleKey = userRoleKey;
       this.userRoleDescription = userRoleDescription;
       this.attribute1 = attribute1;
       this.attribute2 = attribute2;
       this.attribute3 = attribute3;
       this.attribute4 = attribute4;
       this.attribute5 = attribute5;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.itgUsersAlls = itgUsersAlls;
       //this.itgProjectsAlls = itgProjectsAlls;
    }
   
    public Integer getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }
    public ItgWorkArea getItgWorkArea() {
        return this.itgWorkArea;
    }
    
    public void setItgWorkArea(ItgWorkArea itgWorkArea) {
        this.itgWorkArea = itgWorkArea;
    }
    public String getUserRoleName() {
        return this.userRoleName;
    }
    
    public void setUserRoleName(String userRoleName) {
        this.userRoleName = userRoleName;
    }
    public String getUserRoleKey() {
        return this.userRoleKey;
    }
    
    public void setUserRoleKey(String userRoleKey) {
        this.userRoleKey = userRoleKey;
    }
    public String getUserRoleDescription() {
        return this.userRoleDescription;
    }
    
    public void setUserRoleDescription(String userRoleDescription) {
        this.userRoleDescription = userRoleDescription;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    public String getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }
    public String getAttribute3() {
        return this.attribute3;
    }
    
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }
    public String getAttribute4() {
        return this.attribute4;
    }
    
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }
    public String getAttribute5() {
        return this.attribute5;
    }
    
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public Set getItgUsersAlls() {
        return this.itgUsersAlls;
    }
    
    public void setItgUsersAlls(Set itgUsersAlls) {
        this.itgUsersAlls = itgUsersAlls;
    }
    /*public Set getItgProjectsAlls() {
        return this.itgProjectsAlls;
    }
    
    public void setItgProjectsAlls(Set itgProjectsAlls) {
        this.itgProjectsAlls = itgProjectsAlls;
    }*/




}


