package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItgUsersAll generated by hbm2java
 */
public class ItgUsersAll  implements java.io.Serializable {


     private Integer userId;
     private ItgCompany itgCompany;
     private ItgPersonalInfoAll itgPersonalInfoAll;
     private ItgUserRolesAll itgUserRolesAll;
     private ItgUsersAll itgUsersAllByIdDirector;
     private ItgUsersAll itgUsersAllByIdManager;
     private ItgUsersAll itgUsersAllByIdLeader;
     private ItgWorkArea itgWorkArea;
     private String username;
     private String password;
     private Date lastLogin;
     private String attribute1;
     private String attribute2;
     private String attribute3;
     private String attribute4;
     private Integer status;
     private Date creationDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;
     private String fullNameDirector;
     private String fullNameManager;
     private String fullNameLeader;
     private String mailDirector;
     private String mailManager;
     private String mailLeader;
     private Date startDateAbsence;
     private Date endDateAbsence;
     private Set itgUsersAllsForIdDirector = new HashSet(0);
     private Set itgUsersAllsForIdManager = new HashSet(0);
     private Set itgUsersAllsForIdLeader = new HashSet(0);
     private Set itgActivitiesAlls = new HashSet(0);

    public ItgUsersAll() {
        itgPersonalInfoAll = new ItgPersonalInfoAll();
        itgWorkArea = new ItgWorkArea();
        itgUserRolesAll = new ItgUserRolesAll(); 
        itgCompany = new ItgCompany();
    }

	
    public ItgUsersAll(ItgPersonalInfoAll itgPersonalInfoAll, ItgUserRolesAll itgUserRolesAll, ItgWorkArea itgWorkArea) {
        this.itgPersonalInfoAll = itgPersonalInfoAll;
        this.itgUserRolesAll = itgUserRolesAll;
        this.itgWorkArea =  itgWorkArea;
    }
    public ItgUsersAll(ItgCompany itgCompany, ItgPersonalInfoAll itgPersonalInfoAll, ItgUserRolesAll itgUserRolesAll, ItgUsersAll itgUsersAllByIdDirector, ItgUsersAll itgUsersAllByIdManager, ItgUsersAll itgUsersAllByIdLeader, ItgWorkArea itgWorkArea, String username, String password, Date lastLogin, String attribute1, String attribute2, String attribute3, String attribute4, Integer status, Date creationDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy, String fullNameDirector, String fullNameManager, String fullNameLeader, String mailDirector, String mailManager, String mailLeader, Date startDateAbsence, Date endDateAbsence, Set itgUsersAllsForIdDirector, Set itgUsersAllsForIdManager, Set itgUsersAllsForIdLeader, Set itgActivitiesAlls) {
       this.itgCompany = itgCompany;
       this.itgPersonalInfoAll = itgPersonalInfoAll;
       this.itgUserRolesAll = itgUserRolesAll;
       this.itgUsersAllByIdDirector = itgUsersAllByIdDirector;
       this.itgUsersAllByIdManager = itgUsersAllByIdManager;
       this.itgUsersAllByIdLeader = itgUsersAllByIdLeader;
       this.itgWorkArea = itgWorkArea;
       this.username = username;
       this.password = password;
       this.lastLogin = lastLogin;
       this.attribute1 = attribute1;
       this.attribute2 = attribute2;
       this.attribute3 = attribute3;
       this.attribute4 = attribute4;
       this.status = status;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.fullNameDirector = fullNameDirector;
       this.fullNameManager = fullNameManager;
       this.fullNameLeader = fullNameLeader;
       this.mailDirector = mailDirector;
       this.mailManager = mailManager;
       this.mailLeader = mailLeader;
       this.startDateAbsence = startDateAbsence;
       this.endDateAbsence = endDateAbsence;
       this.itgUsersAllsForIdDirector = itgUsersAllsForIdDirector;
       this.itgUsersAllsForIdManager = itgUsersAllsForIdManager;
       this.itgUsersAllsForIdLeader = itgUsersAllsForIdLeader;
       this.itgActivitiesAlls = itgActivitiesAlls;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    
    public ItgCompany getItgCompany() {
        return this.itgCompany;
    }
    
    public void setItgCompany(ItgCompany itgCompany) {
        this.itgCompany = itgCompany;
    }
    public ItgPersonalInfoAll getItgPersonalInfoAll() {
        return this.itgPersonalInfoAll;
    }
    
    public void setItgPersonalInfoAll(ItgPersonalInfoAll itgPersonalInfoAll) {
        this.itgPersonalInfoAll = itgPersonalInfoAll;
    }
    public ItgUserRolesAll getItgUserRolesAll() {
        return this.itgUserRolesAll;
    }
    
    public void setItgUserRolesAll(ItgUserRolesAll itgUserRolesAll) {
        this.itgUserRolesAll = itgUserRolesAll;
    }
    public ItgWorkArea getItgWorkArea() {
        return this.itgWorkArea;
    }
    
    public ItgUsersAll getItgUsersAllByIdDirector() {
        return this.itgUsersAllByIdDirector;
    }
    
    public void setItgUsersAllByIdDirector(ItgUsersAll itgUsersAllByIdDirector) {
        this.itgUsersAllByIdDirector = itgUsersAllByIdDirector;
    }
    public ItgUsersAll getItgUsersAllByIdManager() {
        return this.itgUsersAllByIdManager;
    }
    
    public void setItgUsersAllByIdManager(ItgUsersAll itgUsersAllByIdManager) {
        this.itgUsersAllByIdManager = itgUsersAllByIdManager;
    }
    public ItgUsersAll getItgUsersAllByIdLeader() {
        return this.itgUsersAllByIdLeader;
    }
    
    public void setItgUsersAllByIdLeader(ItgUsersAll itgUsersAllByIdLeader) {
        this.itgUsersAllByIdLeader = itgUsersAllByIdLeader;
    }
    
    public void setItgWorkArea(ItgWorkArea itgWorkArea) {
        this.itgWorkArea = itgWorkArea;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    public String getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }
    public String getAttribute3() {
        return this.attribute3;
    }
    
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }
    public String getAttribute4() {
        return this.attribute4;
    }
    
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    
    public String getFullNameDirector() {
        return this.fullNameDirector;
    }
    
    public void setFullNameDirector(String fullNameDirector) {
        this.fullNameDirector = fullNameDirector;
    }
    public String getFullNameManager() {
        return this.fullNameManager;
    }
    
    public void setFullNameManager(String fullNameManager) {
        this.fullNameManager = fullNameManager;
    }
    public String getFullNameLeader() {
        return this.fullNameLeader;
    }
    
    public void setFullNameLeader(String fullNameLeader) {
        this.fullNameLeader = fullNameLeader;
    }
    public String getMailDirector() {
        return this.mailDirector;
    }
    
    public void setMailDirector(String mailDirector) {
        this.mailDirector = mailDirector;
    }
    public String getMailManager() {
        return this.mailManager;
    }
    
    public void setMailManager(String mailManager) {
        this.mailManager = mailManager;
    }
    public String getMailLeader() {
        return this.mailLeader;
    }
    
    public void setMailLeader(String mailLeader) {
        this.mailLeader = mailLeader;
    }
    public Date getStartDateAbsence() {
        return this.startDateAbsence;
    }
    
    public void setStartDateAbsence(Date startDateAbsence) {
        this.startDateAbsence = startDateAbsence;
    }
    public Date getEndDateAbsence() {
        return this.endDateAbsence;
    }
    
    public void setEndDateAbsence(Date endDateAbsence) {
        this.endDateAbsence = endDateAbsence;
    }
    public Set getItgUsersAllsForIdDirector() {
        return this.itgUsersAllsForIdDirector;
    }
    
    public void setItgUsersAllsForIdDirector(Set itgUsersAllsForIdDirector) {
        this.itgUsersAllsForIdDirector = itgUsersAllsForIdDirector;
    }
    public Set getItgUsersAllsForIdManager() {
        return this.itgUsersAllsForIdManager;
    }
    
    public void setItgUsersAllsForIdManager(Set itgUsersAllsForIdManager) {
        this.itgUsersAllsForIdManager = itgUsersAllsForIdManager;
    }
    public Set getItgUsersAllsForIdLeader() {
        return this.itgUsersAllsForIdLeader;
    }
    
    public void setItgUsersAllsForIdLeader(Set itgUsersAllsForIdLeader) {
        this.itgUsersAllsForIdLeader = itgUsersAllsForIdLeader;
    }
    public Set getItgActivitiesAlls() {
        return this.itgActivitiesAlls;
    }
    
    public void setItgActivitiesAlls(Set itgActivitiesAlls) {
        this.itgActivitiesAlls = itgActivitiesAlls;
    }




}


