package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItgVouchersStatus generated by hbm2java
 */
public class ItgVouchersStatus  implements java.io.Serializable {


     private Integer voucherId;
     private String nameStatus;
     private String description;
     private String attribute1;
     private Date attribute2;
     private Date creationDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;
     private Set itgExpenseReportsAlls = new HashSet(0);

    public ItgVouchersStatus() {
    }

    public ItgVouchersStatus(String nameStatus, String description, String attribute1, Date attribute2, Date creationDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy, Set itgExpenseReportsAlls) {
       this.nameStatus = nameStatus;
       this.description = description;
       this.attribute1 = attribute1;
       this.attribute2 = attribute2;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.itgExpenseReportsAlls = itgExpenseReportsAlls;
    }
   
    public Integer getVoucherId() {
        return this.voucherId;
    }
    
    public void setVoucherId(Integer voucherId) {
        this.voucherId = voucherId;
    }
    public String getNameStatus() {
        return this.nameStatus;
    }
    
    public void setNameStatus(String nameStatus) {
        this.nameStatus = nameStatus;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    public Date getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(Date attribute2) {
        this.attribute2 = attribute2;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public Set getItgExpenseReportsAlls() {
        return this.itgExpenseReportsAlls;
    }
    
    public void setItgExpenseReportsAlls(Set itgExpenseReportsAlls) {
        this.itgExpenseReportsAlls = itgExpenseReportsAlls;
    }




}


