package Model;
// Generated 26/10/2021 05:06:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItgWorkArea generated by hbm2java
 */
public class ItgWorkArea  implements java.io.Serializable {


     private Integer areaId;
     private String nameArea;
     private String description;
     private String attribute1;
     private String attribute2;
     private BigDecimal attribute3;
     private Date creationDate;
     private Long createdBy;
     private Date lastUpdateDate;
     private Long lastUpdatedBy;
     //private Set itgProjectsAlls = new HashSet(0);
     private Set itgUsersAlls = new HashSet(0);
     private Set itgUserRolesAlls = new HashSet(0);

    public ItgWorkArea() {
    }

    public ItgWorkArea(String nameArea, String description, String attribute1, String attribute2, BigDecimal attribute3, Date creationDate, Long createdBy, Date lastUpdateDate, Long lastUpdatedBy, Set itgProjectsAlls, Set itgUsersAlls, Set itgUserRolesAlls) {
       this.nameArea = nameArea;
       this.description = description;
       this.attribute1 = attribute1;
       this.attribute2 = attribute2;
       this.attribute3 = attribute3;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdatedBy = lastUpdatedBy;
       //this.itgProjectsAlls = itgProjectsAlls;
       this.itgUsersAlls = itgUsersAlls;
       this.itgUserRolesAlls = itgUserRolesAlls;
    }
   
    public Integer getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }
    public String getNameArea() {
        return this.nameArea;
    }
    
    public void setNameArea(String nameArea) {
        this.nameArea = nameArea;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAttribute1() {
        return this.attribute1;
    }
    
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    public String getAttribute2() {
        return this.attribute2;
    }
    
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }
    public BigDecimal getAttribute3() {
        return this.attribute3;
    }
    
    public void setAttribute3(BigDecimal attribute3) {
        this.attribute3 = attribute3;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    /*public Set getItgProjectsAlls() {
        return this.itgProjectsAlls;
    }
    
    public void setItgProjectsAlls(Set itgProjectsAlls) {
        this.itgProjectsAlls = itgProjectsAlls;
    }*/
    public Set getItgUsersAlls() {
        return this.itgUsersAlls;
    }
    
    public void setItgUsersAlls(Set itgUsersAlls) {
        this.itgUsersAlls = itgUsersAlls;
    }
    public Set getItgUserRolesAlls() {
        return this.itgUserRolesAlls;
    }
    
    public void setItgUserRolesAlls(Set itgUserRolesAlls) {
        this.itgUserRolesAlls = itgUserRolesAlls;
    }




}


